baseURL = "http://example.org/"
languageCode = "en-us"
title = "Home | IT Security Group"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
#[[menu.main]]
#name    = "Home"
#url     = "/"
#weight  = 1
[[menu.main]]
name    = "Team"
url     = "team"
weight  = 2  
[[menu.main]]
name    = "Teaching"
url     = "forstudents"
weight  = 3 
#[[menu.main]]
#name    = "child1"
#url     = "child1"
#weight  = 1
#parent  = "Service"

#[[menu.main]]
#name    = "News"
#url     = "blog"
#weight  = 4
[[menu.main]]
name    = "Contact Us"
url     = "contactus"
weight  = 6
[[menu.main]]
name    = "Publications"
url     = "publications"
weight  = 4


# Site Params
[params]
home = "Home"
logo = "images/logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "Airspace Hugo theme"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable  = true
bgImage = "images/securityslider.jpg"
heading = "Welcome to IT Security Group."
description = "Here goes a short description"
# button
#btn     = true
#btnText = "Download More"
#btnURL  = "https://themefisher.com/"

# flip text
[[params.banner.flipText]]
title   = "We can use"
[[params.banner.flipText]]
title   = "this flip text"
[[params.banner.flipText]]
title   = "if you want"

# Homepage About Section
[params.about]
enable  = true
title   = "ABOUT US"
content = "Here goes the about section with a beautiful image"
image   = "images/about/about1.jpg"

# Call to Action
#[params.cta]
#enable  = true
#title   = "SO WHAT YOU THINK ?"
#content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
#btnText = "Contact with me"
#btnURL  = "/contact"

#twitter section
[params.tweet]
enable  = true

# Portfolio Section On Homepage
#[params.portfolio]
#enable  = false
#title   = "Latest Works"
#subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "#"

[[params.socialIcon]]
icon = "ion-social-instagram"
url = "#"

[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "#"
