# See https://github.com/gohugoio/hugoThemes#themetoml for an example
name = "Timer Hugo"
license = "MIT"
licenselink = "https://gitlab.com/pacabarcos/hits-research/-/blob/main/themes/timer-hugo/LICENSE"
description = ""
homepage = "http://example.com/"
demosite = "https://hitsresearch-demo.netlify.app/"
tags = ['landing-page', 'google-analytics', 'fast', 'light', 'white', 'modern', 'business', 'agency-template', 'themefisher', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'company', 'projects', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'gethugothemes']
features = ['bootstrap','responsive','fast']
min_version = "0.60.0"

[author]
  name = "Pritilata Saha"
  homepage = ""